server:
    port: 5555
spring:
    application:
        name: gateway-zuul
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/
zuul:
    routes:
        orders:
            path: /service-order/**
            serviceId: service-order
        shares:
            path: /service-share/**
            serviceId: service-share